/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Cliente;
import DatabaseDAO.Postgre_SQL.PostgreSQL_Cliente;
import DatabaseSingleton.PostgreSQL_Singleton;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class FormularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCliente
     */
    public FormularioCliente() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_tel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        tf_dia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblminimizar = new javax.swing.JLabel();
        jl_cerrar = new javax.swing.JLabel();
        lblTituloFC = new javax.swing.JLabel();
        tf_Apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_mes = new javax.swing.JTextField();
        tf_anio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        tf_caract = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        tf_DT = new javax.swing.JTextField();
        tf_ZT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_Ocup = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        tf_DV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_ZV = new javax.swing.JTextField();
        jl_cancelar = new javax.swing.JLabel();
        jl_registrar = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fondoFormularioCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Cliente");
        setUndecorated(true);
        setSize(new java.awt.Dimension(850, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        tf_tel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_tel.setForeground(new java.awt.Color(255, 255, 255));
        tf_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_tel.setText("Telefono sin 15");
        tf_tel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_tel.setOpaque(false);
        tf_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telActionPerformed(evt);
            }
        });
        jPanel1.add(tf_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 180, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 200, 10));

        tf_dia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_dia.setForeground(new java.awt.Color(255, 255, 255));
        tf_dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_dia.setText("Dia");
        tf_dia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_dia.setOpaque(false);
        tf_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_diaActionPerformed(evt);
            }
        });
        jPanel1.add(tf_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 60, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono Particular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 150, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 200, 10));

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizarIconFC.png"))); // NOI18N
        lblminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblminimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 30, 20));

        jl_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrarIconFC.png"))); // NOI18N
        jl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jl_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 20));

        lblTituloFC.setFont(new java.awt.Font("Arial Black", 0, 28)); // NOI18N
        lblTituloFC.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloFC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoNaturaFC.png"))); // NOI18N
        lblTituloFC.setText("Formulario de Cliente");
        jPanel1.add(lblTituloFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 90));

        tf_Apellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_Apellido.setForeground(new java.awt.Color(255, 255, 255));
        tf_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_Apellido.setOpaque(false);
        tf_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 300, 20));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de Trabajo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 370, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, 30));

        tf_mes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_mes.setForeground(new java.awt.Color(255, 255, 255));
        tf_mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_mes.setText("Mes");
        tf_mes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_mes.setOpaque(false);
        tf_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mesActionPerformed(evt);
            }
        });
        jPanel1.add(tf_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 60, 20));

        tf_anio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_anio.setForeground(new java.awt.Color(255, 255, 255));
        tf_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_anio.setText("Año");
        tf_anio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_anio.setOpaque(false);
        tf_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anioActionPerformed(evt);
            }
        });
        jPanel1.add(tf_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 60, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("/");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 20, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("_");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 20, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, 30));

        tf_Nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        tf_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_Nombre.setOpaque(false);
        tf_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 300, 20));

        tf_caract.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tf_caract.setForeground(new java.awt.Color(255, 255, 255));
        tf_caract.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_caract.setText("caract");
        tf_caract.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_caract.setOpaque(false);
        tf_caract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_caractActionPerformed(evt);
            }
        });
        jPanel1.add(tf_caract, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 60, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 20, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 10));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Datos Personales");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 170, 180, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 200, 10));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Direccion de Trabajo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 30));

        tf_DT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_DT.setForeground(new java.awt.Color(255, 255, 255));
        tf_DT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_DT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_DT.setOpaque(false);
        tf_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_DTActionPerformed(evt);
            }
        });
        jPanel1.add(tf_DT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 390, 20));

        tf_ZT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_ZT.setForeground(new java.awt.Color(255, 255, 255));
        tf_ZT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_ZT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_ZT.setOpaque(false);
        tf_ZT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ZTActionPerformed(evt);
            }
        });
        jPanel1.add(tf_ZT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 390, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Zona de Trabajo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 150, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ocupacion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 150, 30));

        tf_Ocup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_Ocup.setForeground(new java.awt.Color(255, 255, 255));
        tf_Ocup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Ocup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_Ocup.setOpaque(false);
        tf_Ocup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_OcupActionPerformed(evt);
            }
        });
        jPanel1.add(tf_Ocup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 390, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 200, 10));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Datos de Vivienda");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 540, 180, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 200, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Direccion de Vivienda");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 160, 30));

        tf_DV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_DV.setForeground(new java.awt.Color(255, 255, 255));
        tf_DV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_DV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_DV.setOpaque(false);
        tf_DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_DVActionPerformed(evt);
            }
        });
        jPanel1.add(tf_DV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 390, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Registrar");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 758, 90, 30));

        tf_ZV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tf_ZV.setForeground(new java.awt.Color(255, 255, 255));
        tf_ZV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_ZV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tf_ZV.setOpaque(false);
        tf_ZV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ZVActionPerformed(evt);
            }
        });
        jPanel1.add(tf_ZV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 390, 20));

        jl_cancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jl_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        jl_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelarIcon.png"))); // NOI18N
        jl_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_cancelarMouseClicked(evt);
            }
        });
        jPanel1.add(jl_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 60, 60));

        jl_registrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jl_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jl_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aceptarIcon.png"))); // NOI18N
        jl_registrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jl_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_registrarMouseClicked(evt);
            }
        });
        jPanel1.add(jl_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 60, 60));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Zona de Vivienda");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 150, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Cancelar");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 760, 90, 30));

        fondoFormularioCliente.setBackground(new java.awt.Color(255, 255, 255));
        fondoFormularioCliente.setForeground(new java.awt.Color(255, 255, 255));
        fondoFormularioCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoFormCliente.png"))); // NOI18N
        fondoFormularioCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(fondoFormularioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setState(FormularioCliente.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void jl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jl_cerrarMouseClicked

    private void tf_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ApellidoActionPerformed

    private void tf_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telActionPerformed

    private void tf_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_diaActionPerformed

    private void tf_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mesActionPerformed

    private void tf_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anioActionPerformed

    private void tf_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreActionPerformed

    private void tf_caractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_caractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_caractActionPerformed

    private void tf_DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_DTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_DTActionPerformed

    private void tf_ZTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ZTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ZTActionPerformed

    private void jl_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_cancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jl_cancelarMouseClicked

    private void jl_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registrarMouseClicked
        int     flag = 1; // Este flag se utiliza para ver si se dio de alta o no, en caso afirmativo se cierra el panel, si no, se deja para arreglar los datos.
        int     age = 2020 - Integer.parseInt(tf_anio.getText()); // se calcula la edad
        Short   cod = 0; // se crea un short cod para pasar al constructor, pero luego no se utiliza, ya que la BD calcula el cod
        String  apel = tf_Apellido.getText();
        String  nom =  tf_Nombre.getText();
        short   edad = (short)age;
        String  fnac = tf_anio.getText() + "-" + tf_mes.getText() + "-" + tf_dia.getText(); // YYYY-MM-DD
        String  tel =  tf_caract.getText()+ "-" + tf_tel.getText(); // Caracteristica-Nro
        String  DV =   tf_DV.getText();
        String  ZV =   tf_ZV.getText();
        String  DT =   tf_DT.getText();
        String  ZT =   tf_ZT.getText();
        String  ocup = tf_Ocup.getText();
        BigDecimal saldo = null;
        
        Cliente nuevo_cliente;
        nuevo_cliente = new Cliente(apel,nom,edad,fnac,tel,DV,ZV);
        try {
            PostgreSQL_Cliente DAO_Cliente = new PostgreSQL_Cliente (PostgreSQL_Singleton.getInstance().getConnection());
            DAO_Cliente.insertar(nuevo_cliente);
        } catch (SQLException ex) {
            Logger.getLogger(FormularioCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jl_registrarMouseClicked

    private void tf_ZVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ZVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ZVActionPerformed

    private void tf_DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_DVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_DVActionPerformed

    private void tf_OcupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_OcupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_OcupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoFormularioCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jl_cancelar;
    private javax.swing.JLabel jl_cerrar;
    private javax.swing.JLabel jl_registrar;
    private javax.swing.JLabel lblTituloFC;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_DT;
    private javax.swing.JTextField tf_DV;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_Ocup;
    private javax.swing.JTextField tf_ZT;
    private javax.swing.JTextField tf_ZV;
    private javax.swing.JTextField tf_anio;
    private javax.swing.JTextField tf_caract;
    private javax.swing.JTextField tf_dia;
    private javax.swing.JTextField tf_mes;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}
