/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Nicolas
 */
public class SeleccionarCantidad extends javax.swing.JFrame implements ChangeListener{

    /**
     * Creates new form SeleccionarCantidad
     */
    public SeleccionarCantidad() {
        initComponents();
        int a= 2;
        int b= 5;
        sliderCantidad.setMinimum(0);
        sliderCantidad.setMaximum(50);
        sliderCantidad.setPaintTicks(true);
        sliderCantidad.setMinorTickSpacing(a);
        sliderCantidad.setPaintTrack(true);
        sliderCantidad.setMajorTickSpacing(b);
        sliderCantidad.setPaintLabels(true);
        sliderCantidad.addChangeListener(this);
        cantidad.setText("Cantidad: " + sliderCantidad.getValue());
        warning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sliderCantidad = new javax.swing.JSlider();
        aceptarCantidad = new javax.swing.JButton();
        cancelarCantidad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sliderCantidad.setMaximum(50);
        sliderCantidad.setPaintLabels(true);
        sliderCantidad.setPaintTicks(true);
        sliderCantidad.setValue(25);
        sliderCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sliderCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderCantidad.setOpaque(false);
        jPanel1.add(sliderCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, -1));

        aceptarCantidad.setText("ACEPTAR");
        aceptarCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarCantidadMouseClicked(evt);
            }
        });
        jPanel1.add(aceptarCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, -1));

        cancelarCantidad.setText("CANCELAR");
        jPanel1.add(cancelarCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese la cantidad deseada:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 90));

        cantidad.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad.setText("Cantidad:");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 30));

        warning.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(204, 0, 51));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warning.setText("La cantidad no puede ser cero");
        jPanel1.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarCantidadMouseClicked
        // TODO add your handling code here:
        
        
        int cant = sliderCantidad.getValue();
        if(cant!=0){
            this.setVisible(false);
            Principal.cantidadPedido = cant;
        }
        else{
            warning.setVisible(true);
        }
        
        
    }//GEN-LAST:event_aceptarCantidadMouseClicked

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCantidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarCantidad().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCantidad;
    private javax.swing.JButton cancelarCantidad;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider sliderCantidad;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent ce) {
        cantidad.setText("Cantidad: " + sliderCantidad.getValue());
    }
}
